// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATmM_1WW61xebxkXFSJa0DA1QouZsKIA0',
    appId: '1:597923914158:web:98b2eeddab14601389a83f',
    messagingSenderId: '597923914158',
    projectId: 'kosen-guide-72d81',
    authDomain: 'kosen-guide-72d81.firebaseapp.com',
    storageBucket: 'kosen-guide-72d81.firebasestorage.app',
    measurementId: 'G-1WEZ6VZ7TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxa1x8uww9umkYVuWvY4cytOZUrBmRIf8',
    appId: '1:597923914158:android:4bda02fd40d307b189a83f',
    messagingSenderId: '597923914158',
    projectId: 'kosen-guide-72d81',
    storageBucket: 'kosen-guide-72d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMiPhBWrF6-LcHA0WCwBGHdXYwczHRws',
    appId: '1:597923914158:ios:e811d0add4bbf7ea89a83f',
    messagingSenderId: '597923914158',
    projectId: 'kosen-guide-72d81',
    storageBucket: 'kosen-guide-72d81.firebasestorage.app',
    iosBundleId: 'com.example.kosenGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMiPhBWrF6-LcHA0WCwBGHdXYwczHRws',
    appId: '1:597923914158:ios:e811d0add4bbf7ea89a83f',
    messagingSenderId: '597923914158',
    projectId: 'kosen-guide-72d81',
    storageBucket: 'kosen-guide-72d81.firebasestorage.app',
    iosBundleId: 'com.example.kosenGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATmM_1WW61xebxkXFSJa0DA1QouZsKIA0',
    appId: '1:597923914158:web:31a6fbe8bbbbc1ca89a83f',
    messagingSenderId: '597923914158',
    projectId: 'kosen-guide-72d81',
    authDomain: 'kosen-guide-72d81.firebaseapp.com',
    storageBucket: 'kosen-guide-72d81.firebasestorage.app',
    measurementId: 'G-HNJ57MNL77',
  );

}